image: java:8

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
      - chmod +x ./gradlew 
      - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar

tests:
  stage: test
  script:
     - export SPRING_PROFILES_ACTIVE=integration_test;
     - chmod +x ./gradlew 
     - ./gradlew test

deploy:
  stage: deploy
  script:
     - mv build/libs/*.jar /opt/ttb
     - echo $gitlab_runner_password | sudo -S systemctl restart appservice