version: '2'
services:
  ttb:
    container_name: ttb-api
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  postgres:
    image: postgres
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=ttb
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres